<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <RootNamespace>CardLocalizationAnalyzer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile
      Include="..\LocalizationAnalyzer\LocalizationCodeFixProvider.cs"
      Link="LocalizationCodeFixProvider.cs"
    />
    <Compile Include="..\LocalizationAnalyzer\Localization.cs" Link="Localization.cs" />
    <PackageReference
      Include="Microsoft.CodeAnalysis.CSharp.Workspaces"
      Version="4.14.0"
      PrivateAssets="all"
    />
    <PackageReference
      Include="Microsoft.CodeAnalysis.Analyzers"
      Version="3.11.0"
      PrivateAssets="all"
    />
    <PackageReference
      Include="System.Composition.AttributedModel"
      Version="9.0.0"
      PrivateAssets="all"
    />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" />
    <Reference
      Include="Newtonsoft.Json"
      HintPath="$(NuGetPackageRoot)newtonsoft.json\13.0.3\lib\netstandard2.0\Newtonsoft.Json.dll"
      Private="true"
      Condition="Exists('$(NuGetPackageRoot)newtonsoft.json\13.0.3\lib\netstandard2.0\Newtonsoft.Json.dll')"
    />
    <None
      Include="$(NuGetPackageRoot)newtonsoft.json\13.0.3\lib\netstandard2.0\Newtonsoft.Json.dll"
      Link="Newtonsoft.Json.dll"
      CopyToOutputDirectory="PreserveNewest"
      Condition="Exists('$(NuGetPackageRoot)newtonsoft.json\13.0.3\lib\netstandard2.0\Newtonsoft.Json.dll')"
    />
  </ItemGroup>
</Project>
